name: Build and Publish Microsoft-Rewards Image

# Se ejecuta manualmente o por cron (cada hora) o por push a tu fork
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # cada día a las 00:00 UTC
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream repository (source)
        uses: actions/checkout@v4
        with:
          repository: LightZirconite/Microsoft-Rewards-Script
          path: source

      - name: Show upstream latest commit
        run: |
          cd source
          echo "Upstream branch commit:"
          git rev-parse --short HEAD
          git log -1 --oneline

      - name: Set up QEMU (multi-arch) - optional
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./source
          file: ./source/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microsoft-rewards-script:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microsoft-rewards-script:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/microsoft-rewards-script:latest
          cache-to: type=inline
